version: '3.3'

services: 
  server:
    build: .
    depends_on: 
      - mysql
    volumes:
      - ./src:/usr/src/app/src
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./package.json:/usr/src/app/package.json
    ports: 
      - 3001:3000

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nodeapp
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306